### ISSUE TITLE
Uncaught ReferenceError: Bolt is not defined

### ISSUE THREAD

**Issue by helman** [rossriley/bolt-extension-formeditor#13]
Hi @rossriley, I am seeing a javascript error even the form editor is working.

the error `formeditor.js?8d8663535f:1 Uncaught ReferenceError: Bolt is not defined` showing in every page (admin)

tested on:
Bolt Forms Editor v2.0
Bolt Forms v3.02
Bolt v3.0.8

**Comment by navelpluisje** [comment]
Had the same issue over here. Currently working on a PR which resolves this issue and some style improvements. 
That's the same reason you're not able to add a field like #13

**Comment by navelpluisje** [comment]
This one is fixed by PR #14 and can be closed
